### ISSUE TITLE
Log the command line

### ISSUE THREAD

**Issue by rickyegeland** [ktindiana/sphinxval#102]
I just came back to a test that I had run on the CCMC sep-validation and couldn't remember what I used for inputs to sphinxval.  It would be good to have sphinxval log the command line it was called with so the `--ModelList` and `--DataList` and other important options are recorded.

**Comment by ktindiana** [comment]
Resolved with commit [942b3f1](https://github.com/ktindiana/sphinxval/commit/942b3f1185e272baa34035127f6b39cf4b1971fd)
