### ISSUE TITLE
Fix logging of json file reading failures

### ISSUE THREAD

**Issue by rickyegeland** [ktindiana/sphinxval#105]
Currently if the loading of a json fails, the file which caused the failure does not make it into the logs.  This makes problems difficult to debug when the list of files is in the millions.  The file name to be loaded should be logged before the load is attempted.

**Comment by ktindiana** [comment]
Resolved with commit [942b3f1](https://github.com/ktindiana/sphinxval/commit/942b3f1185e272baa34035127f6b39cf4b1971fd)
