### ISSUE TITLE
Unit test request for thresholds

### ISSUE THREAD

**Issue by ktindiana** [ktindiana/sphinxval#129]
@lukestegeman Please make:

-  a unit test for a json with only a peak_intensity field. 
- a second test using the same json, but adding in an all_clear block that forgets to include the threshold field. 

"all_clear":{"all_clear_boolean":true,"threshold":10,"threshold_units":"pfu"}
}

These tests will test a bug fix that allows peak_intensity only forecasts to go through. 
I am concerned that if there is a bad json that forgets to put a threshold in a block where there should be one (e.g. all clear, probability, etc), then this fix might somehow allow that forecasted quantity to get evaluated when it really shouldn't be.

**Comment by rickyegeland** [comment]
Fixed by #130 via #131.
