### ISSUE TITLE
Feature Request: Advanced Warning Time

### ISSUE THREAD

**Issue by ktindiana** [ktindiana/sphinxval#16]
Calculate AWT following methodology in previous version of validation code.

**Comment by rickyegeland** [comment]
Can you outline the methodology here?

**Comment by ktindiana** [comment]
Advanced Warning Time has been added to the code. AWT is calculated if models provide forecasts for:
All Clear
Threshold Crossing Time
Start Time
Peak Intensity
Peak Intensity Max

AWT is calculated for each of the forecast types, so if a model only produces one type of forecast, the AWT will always be reported with respect to:
AWT to Observed Threshold Crossing Time
AWT to Observed Start Time (in case somehow a modeler applies different thresholds to calculate start time and threshold crossing time?)
If a peak flux forecast, then Peak Intensity Time or Peak Intensity Max Time

AWT is calculated by selecting the first in a *continuous* series of forecasts leading up to an SEP event that predict an SEP event will occur.
