### ISSUE TITLE
Checking for repeat forecasts

### ISSUE THREAD

**Issue by ktindiana** [ktindiana/sphinxval#41]
Checking should be implemented to look for repeated forecasts or forecasts from the same model covering exactly the same prediction window in the same energy channel. e.g. ADEPT 1hr and 6hr forecasts wrote over each other because they had the same short name and forecast periods.

This will additionally likely identify a number of MAG4 forecasts as it has the behavior of repeating exactly the last forecast if no new data has been received.

**Comment by rickyegeland** [comment]
What should the behavior of the check be?  Crash when found?  Create a unique ID and count them all?

**Comment by ktindiana** [comment]
Yes, what should the behavior be and what should we check? What should be unique? Issue time, prediction window, forecasted values? What if the issue time is different but all the other values remain the same (as in the MAG4 behavior)? What should be considered a valid repeat and what is not?

**Comment by ktindiana** [comment]
Marking with "Help wanted" label to determine appropriate logic, then I will code it up.

**Comment by ktindiana** [comment]
This is now handled when the SPHINX_dataframe is created and duplicate forecasts are removed.

**Comment by ktindiana** [comment]
Resolved with commit [942b3f1](https://github.com/ktindiana/sphinxval/commit/942b3f1185e272baa34035127f6b39cf4b1971fd)
