### ISSUE TITLE
Bug: Report note for Time Profile Metrics is irrelevant

### ISSUE THREAD

**Issue by rickyegeland** [ktindiana/sphinxval#43]
The Time Profile Metric has the note:

```
Metrics for Observed Time - Predicted Time are in hours.
Negative values indicate predicted time is later than observed.
Positive values indicate predicted time is earlier than observed.
```

But this table contains flux difference metrics, not time differences.  The note should be like the one in peak flux, etc.

**Comment by lukestegeman** [comment]
Fixed. Replaced Time Profile metrics description with same description provided in Fluence section.

**Comment by ktindiana** [comment]
Report text has been changed to appropriately describe each section.
