### ISSUE TITLE
Feature Request: Add in missing metrics that have placeholders but are not being calculated

### ISSUE THREAD

**Issue by ktindiana** [ktindiana/sphinxval#48]
e.g. Spearman correlation coefficient, symmetric skill scores, skill scores for extreme events, etc

**Comment by ktindiana** [comment]
Flux:

- Spearman Correlation Coefficient
- Mean Accuracy Ratio
- Median Symmetric Accuracy

Probability:

- Brier Skill Score
- Linear Correlation Coefficient
- Rank Order Correlation Coefficient

Other worthwhile metrics? Look into Sadykov Skill Score.

**Comment by rickyegeland** [comment]
Add All Clear / contingency metric symmetric extreme dependency score (SEDS).  See Liemohn et al. 2021, RSME is not enough, JASTP Sec 3.2.5 "Extremes".

SEDS = ln( (a+b) / N ) + ln( (a+c) / N) / ln( a/N ) -1

where a = Hits, b = False Alarms, c = Misses, d = Correct Negatives, N = a + b + c + d

**Comment by rickyegeland** [comment]
@claya71 is it done already in #57 ?  Is the Brier Skill Score still missing?

**Comment by claya71** [comment]
BSS has been added, in conjunction with the changes that added ROC curves. I believe the spirit of this issue has been resolved.
