### ISSUE TITLE
Error in HSS

### ISSUE THREAD

**Issue by rickyegeland** [ktindiana/sphinxval#54]
In metrics.py `calc_contingency_bool()` the `HSS` metric has a sign error.  It should be:

```python
'HSS': check_div(2.0 * (h*c - f*m), ((h+m) * (m+c) + (h+f) * (f+c))),
```

It was corrected in `calc_contingency()` above, but not here in the function that is actually used in validation.py.

**Comment by claya71** [comment]
Fixed, will push changes to metrics.py after implementation of Brier Skill Score using last SC climatology rate

**Comment by ktindiana** [comment]
Verified that Clayton fixed this and it was included in the merge.
