### ISSUE TITLE
Merge calc_contingency() and calc_contingency_bool()

### ISSUE THREAD

**Issue by rickyegeland** [ktindiana/sphinxval#55]
In metrics.py, there are two functions that are copy-and-paste copies of each other, `calc_contingency()`, and `calc_contingency_bool()`.  The former should just call the latter once the thresholds are applied, to reduce redundancy in the code.

**Comment by claya71** [comment]
I will implement this change

**Comment by ktindiana** [comment]
Clayton did this and I added a line that was left out to make it work.
