### ISSUE TITLE
Simplify --resume interface

### ISSUE THREAD

**Issue by rickyegeland** [ktindiana/sphinxval#73]
The help of `sphinx.py` currently reads:

```
  --resume              Specify resume to add forecasts to an existing
                        dataframe and recalculate metrics.
  --DataFrame DATAFRAME
                        Filename of existing Pandas DataFrame containing the
                        results of a previous SPHINX run in pkl format. Must
                        specify if choose resume.
```

Simplify this by requiring the DATAFRAME argument is passed to `--resume`, e.g.

`python bin/sphinx.py --resume SPHINX_dataframe.pkl`

This presumes there is no use-case for running with `--DataFrame` and without `--resume`.

**Comment by ktindiana** [comment]
Resolved with commit [942b3f1](https://github.com/ktindiana/sphinxval/commit/942b3f1185e272baa34035127f6b39cf4b1971fd)
