### ISSUE TITLE
Feature Request: Include all matching information in SPHINX data frame

### ISSUE THREAD

**Issue by ktindiana** [ktindiana/sphinxval#8]
The output to screen results in very big log files if saved. The very verbose Matching Reports take up a lot of GB. Better to save the matching information in a more compact way in the SPHINX Dataframe.

Also note that the json and md output is large and may not be needed.

**Comment by rickyegeland** [comment]
json and md output turned out to be expensive to compute as well.  I propose a separate feature request to make separate flags to enable these output types.

**Comment by rickyegeland** [comment]
@ktindiana wasn't there progress on this?  What commits?

**Comment by ktindiana** [comment]
@rickyegeland No progress has been made on this. Matching information remains in the output to screen (i.e. log file) and has not been incorporated into the dataframe.

**Comment by rickyegeland** [comment]
@ktindiana is this one done in the logging update (commit a2717a0)?

**Comment by ktindiana** [comment]
Resolved with commit [942b3f1](https://github.com/ktindiana/sphinxval/commit/942b3f1185e272baa34035127f6b39cf4b1971fd)
